version: '3'
services: 
  web_app:
    image: manrodri/yelp-camp
    container_name: yelpCamp
    build: ./yelpCamp
    command: node app.js
    ports: 
      - "3000:3000"
    restart: always
    links:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db            
  
  adminmongo:
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"
